<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxcore.js'}}"></script>
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxbuttons.js'}}"></script>
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxcheckbox.js'}}"></script>
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.js'}}"></script>
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.columnsresize.js'}}"></script> 
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.selection.js'}}"></script>	
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.filter.js'}}"></script>		
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxdata.js'}}"></script>	
	<script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxdata.js'}}"></script> 
    <script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxdata.export.js'}}"></script> 
    <script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.export.js'}}"></script> 
    <script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/jqxgrid.sort.js'}}"></script> 
    <script type="text/javascript" src="{{ BACKEND.'js/jqwidgets/scripts/demos.js'}}"></script>
